--1) CNO이 PK인 COURSE_PK 테이블을 생성하세요.(1번 방식으로)
CREATE TABLE COURSE_PK(
    CNO     VARCHAR2(8) PRIMARY KEY
)
;
--2) PNO이 PK인 PROFESSOR_PK 테이블을 생성하세요.(2번 방식으로)
CREATE TABLE PROFESSOR_PK(
    PNO     VARCHAR2(8),
    CONSTRAINT PK_PROFESSOR_PNO PRIMARY KEY(PNO)
)
;

--3) PF_TEMP 테이블에 PNO을 PK로 추가하세요.
ALTER TABLE PF_TEMP
    ADD CONSTRAINT PK_PF_TEMP_PNO PRIMARY KEY(PNO)
;

RENAME COURSE_PRFESSOR TO COURSE_PROFESSOR;
DELETE FROM COURSE_PROFESSOR
 WHERE PNUM IS NULL;
COMMIT;
--4) COURSE_PROFESSOR 테이블에 CNO, PNO을 PK로 추가하세요. CNO -> CNUM, PNO -> PNUM
ALTER TABLE COURSE_PROFESSOR
    ADD CONSTRAINT PK_COURSE_PROFESSOR_CNO_PNO PRIMARY KEY(CNUM, PNUM)
;

--5) BOARD_NO(NUMBER)를 PK로 갖으면서 BOARD_TITLE(VARCHAR2(200)), BOARD_CONTENT(VARCHAR2(2000)), 
--   BOARD_WRITER(VARCHAR2(20)), BOARD_FRGT_DATE(DATE), BOARD_LMDF_DATE(DATE) 컬럼을 갖는 T_BOARD 테이블을 생성하세요.
CREATE TABLE T_BOARD (
    BOARD_NO        NUMBER CONSTRAINT PK_BOARD_NO PRIMARY KEY,
    BOARD_TITLE     VARCHAR2(200),
    BOARD_CONTENT   VARCHAR2(2000),
    BOARD_WRITER    VARCHAR2(20),
    BOARD_FRGT_DATE DATE,
    BOARD_LMDF_DATE DATE
)
;
--6) BOARD_NO(NUMBER), BOARD_FILE_NO(NUMBER)를 PK로 갖으면서 BOARD_FILE_NM(VARCHAR2(200)), BOARD_FILE_PATH(VARCHAR2(2000)),
--   ORIGIN_FILE_NM(VARCHAR2(200)) 컬럼을 갖는 T_BOARD_FILE 테이블을 생성하세요.
CREATE TABLE T_BOARD_FILE (
    BOARD_NO        NUMBER,
    BOARD_FILE_NO   NUMBER,
    BOARD_FILE_NM   VARCHAR2(200),
    BOARD_FILE_PATH VARCHAR2(2000),
    ORIGIN_FILE_NM  VARCHAR2(200),
    CONSTRAINT PK_BOARD_BN_BFN PRIMARY KEY(BOARD_NO, BOARD_FILE_NO)
)
;
SELECT *
  FROM T_BOARD_FILE
;

--7) 다음 구조를 갖는 테이블을 생성하세요.
--   T_SNS                              T_SNS_DETAIL                        T_SNS_UPLOADED
--   SNS_NO(PK)    SNS_NM               SNS_NO(PK, FK)   SNS_BEN            SNS_NO(PK, FK)    SNS_UPL_NO(PK)
--     1            페북                   1               4000                   1                  1
--     2           인스타                  2               10000                  1                  2
--     3           트위터                  3               30000                  2                  1
--                                                                               2                  2
CREATE TABLE T_SNS(
    SNS_NO  NUMBER  PRIMARY KEY,
    SNS_NM  VARCHAR2(20)
)
;
INSERT INTO T_SNS
VALUES (1, '페북');
INSERT INTO T_SNS
VALUES (2, '인스타');
INSERT INTO T_SNS
VALUES (3, '트위터');

COMMIT;

CREATE TABLE T_SNS_DETAIL(
    SNS_NO  NUMBER,
    SNS_BEN NUMBER,
    CONSTRAINT PK_T_SNS_DETAIL_SNN PRIMARY KEY(SNS_NO),
    CONSTRAINT FK_T_SNS_DETAIL_SNN FOREIGN KEY(SNS_NO)
        REFERENCES T_SNS(SNS_NO)
)
;

SELECT *
  FROM T_SNS_DETAIL
;

CREATE TABLE T_SNS_UPLOADED(
    SNS_NO      NUMBER,
    SNS_UPL_NO  NUMBER,
    CONSTRAINT PK_T_SNS_UPLOADED_SNN_SUN    PRIMARY KEY(SNS_NO, SNS_UPL_NO),
    CONSTRAINT FK_T_SNS_UPLOADED_SNN        FOREIGN KEY(SNS_NO)
        REFERENCES T_SNS(SNS_NO)
)
;

SELECT *
  FROM T_SNS_UPLOADED
;